# Define o tipo de banco de dados
quarkus.datasource.db-kind=postgresql

# Configura as credenciais do seu banco de dados existente
quarkus.datasource.username=postgres
quarkus.datasource.password=renato

# Configura a URL de conexão (ajuste o host, a porta e o nome do banco)
quarkus.datasource.jdbc.url=jdbc:postgresql://database:5432/petshop

# Atualiza a estrutura apenas se necessário, mantendo os dados intactos
quarkus.hibernate-orm.database.generation=update