# Define o tipo de banco de dados
quarkus.datasource.db-kind=postgresql

# Configura as credenciais do seu banco de dados existente
quarkus.datasource.username=postgres
quarkus.datasource.password=renato

# Configura a URL de conexão (ajuste o host, a porta e o nome do banco)
quarkus.datasource.jdbc.url=jdbc:postgresql://database:5432/petshop

# Atualiza a estrutura apenas se necessário, mantendo os dados intactos
quarkus.hibernate-orm.database.generation=update

# Configuração do Cliente REST da Dog CEO
dog-ceo-api/mp-rest/url=https://dog.ceo

# Habilitando recurso de logs em json
# quarkus.log.console.json=true

# Liga o log de SQL no console
quarkus.hibernate-orm.log.sql=true

# Formata o SQL para ficar com quebras de linha e fácil de ler no Portainer
quarkus.hibernate-orm.log.format-sql=true

# Em tese, é para mostrar os valores que estão sendo cadastrados no log
quarkus.hibernate-orm.log.bind-parameters=true

# Ativando exibição de logs coloridos
quarkus.console.color=true

# Formatando outras informações exibidas no log e que são retornadas pelo próprio quarkus
quarkus.log.console.format=%d{HH:mm:ss} %highlight{%-5p} [%c{2.}] %s%e%n

# Recurso para retornar o IP verdadeiro de quem fez a requisição, visto que o docker pode retonar o localhost
quarkus.http.proxy.proxy-address-forwarding=true